### PR TITLE
Tlu, fw24 & more

### PR DESCRIPTION
**Pull request by dreyling**

### CODE REVIEW

**Comment by lhuth** [comment]
Always happy with someone updating docu/configs

**Comment by TCThenna** [comment]
Hi Jan,

one question, why do you always comment out the MIMOSA planeID setting to 0,...,5?

#MimosaID_1 = 0
#MimosaID_2 = 1
#MimosaID_3 = 2
#MimosaID_4 = 3
#MimosaID_5 = 4
#MimosaID_6 = 5

Then, they will be called 1 - 6, and at least in the past, that created some problems for some producers.

**Comment by dreyling** [comment]
Hi @TCThenna 

okay, first, we should reduce the not used ini/conf-parameters in our example files, because they are not used and users get confused. This I am doing at the moment for Ni and TLU producer and move a description of all parameters in a README file as documentation.

Second, you are right that there were some issues in the past! Was it for other producers or EUTelescope? And was starting from 0 or from 1 the correct counting?

**Comment by TCThenna** [comment]
> okay, first, we should reduce the not used ini/conf-parameters in our example files

That's fine of course

> Was it for other producers or EUTelescope?

Sry, I mixed it up, the problem was with processors in eutel.

> And was starting from 0 or from 1 the correct counting?
Starting from 0 was better

**Pull request merged**
